### PR TITLE
Switch to ament_cmake_vendor_package

### PR DESCRIPTION
**Pull request by cottsay**
Part of https://github.com/ament/ament_cmake/pull/429

### CODE REVIEW

**Comment by Yadunund** [comment]
Is `ament_cmake_vendor_package` not distributed on `humble`? 🤔 

Although `main` targets `rolling`, ideally we'd like to have `main` also compile with `humble`.

**Comment by cottsay** [comment]
> Is ament_cmake_vendor_package not distributed on humble?

It is not, though we could probably backport it.

**Comment by cottsay** [comment]
@ros-pull-request-builder retest this please

**Review by Yadunund — APPROVED** [review]
Thanks for backporting `ament_cmake_vendor_package` to humble! CI is passing so I will merge this in.

**Pull request merged**
